# utils/theme.py
LIGHT_THEME = {
    "bg": "#f0f0f0",
    "fg": "#000000",
    "entry_bg": "#ffffff",
    "entry_fg": "#000000",
    "button_bg": "#e0e0e0",
    "button_fg": "#000000",
    "label_bg": "#f0f0f0",
    "label_fg": "#000000",
    "labelframe_bg": "#f0f0f0",
    "labelframe_fg": "#000000",
    "text_bg": "#ffffff",
    "text_fg": "#000000",
    "log_bg": "#ffffff",
    "log_fg": "#000000",
    "warning_bg": "#ffcccc",
    "warning_fg": "#ff0000",
    "bottom_bg": "#ffffff",
    "bottom_fg": "gray",
    "tooltip_bg": "#ffffe0",
    # ttk 样式颜色
    "ttk_bg": "#f0f0f0",
    "ttk_fg": "#000000",
    "ttk_select_bg": "#d0d0d0",
    "ttk_select_fg": "#000000",
    "ttk_field_bg": "#ffffff",
    "ttk_progress_bg": "#4fc3f7",
    "ttk_trough_bg": "#e0e0e0"
}

DARK_THEME = {
    "bg": "#2e2e2e",
    "fg": "#ffffff",
    "entry_bg": "#3e3e3e",
    "entry_fg": "#ffffff",
    "button_bg": "#4e4e4e",
    "button_fg": "#ffffff",
    "label_bg": "#2e2e2e",
    "label_fg": "#ffffff",
    "labelframe_bg": "#2e2e2e",
    "labelframe_fg": "#ffffff",
    "text_bg": "#3e3e3e",
    "text_fg": "#ffffff",
    "log_bg": "#1e1e1e",
    "log_fg": "#ffffff",
    "warning_bg": "#553333",
    "warning_fg": "#ff8888",
    "bottom_bg": "#2e2e2e",
    "bottom_fg": "#aaaaaa",
    "tooltip_bg": "#3e3e3e",
    # ttk 样式颜色
    "ttk_bg": "#2e2e2e",
    "ttk_fg": "#ffffff",
    "ttk_select_bg": "#3a3a3a",
    "ttk_select_fg": "#ffffff",
    "ttk_field_bg": "#3e3e3e",
    "ttk_progress_bg": "#4fc3f7",
    "ttk_trough_bg": "#3a3a3a"
}